### PR TITLE
Provisioning part deux

### PR DESCRIPTION
**Pull request by tpitale**
- [x] clone repo down to server
- [x] install pip/virtualenv dependencies
- [x] configure twitter and mysql in config.json
- [x] figure out how to connect nginx with python
- [x] configure nginx to talk to python app
- [x] figure out "deployment" for python apps?

### CODE REVIEW

**Comment by tpitale** [comment]
Now to just get mysql to work … ugh. The bingo.sql file does not work with this version of mysql. Debugging.

**Comment by tpitale** [comment]
Works! http://104.131.176.194/leaderboard

**Comment by tpitale** [comment]
I think this is all ready to merge … we'll have to make a few other minor tweaks, but it's mostly working.

We also have to load mysql `bingo.sql` by hand, and we still need to load the board.

**Comment by tpitale** [comment]
Next Steps:
- [x] set IP for domain to 104.131.176.194 #20 
- [ ] load board data from csv into database #11 
- [ ] test! #9, #10, #16

**Comment by livlab** [comment]
Ok, I am done with tweaks for now. Let me know if I can do anything to load the data into the DB, otherwise I'll wait for your word on it being done to start testing. 

Oh and if I need to merge branches please let me know (I wasn't sure).

Thank you for all your help!

**Comment by tpitale** [comment]
Do you have a spreadsheet of the board? If so I can add that to the DB in the morning.

**Comment by livlab** [comment]
Yes, pushed it just now: https://github.com/livlab/ias-bingo/blob/master/iasbingo.csv

will update it at a later time with final content but it's good enough to test with.

**Pull request merged**
