### PR TITLE
WIP: Provisioning

### PR DESCRIPTION
**Pull request by tpitale**
Getting started with provisioning for the app by way of chef-solo for use with Digital Ocean.
- [x] Update README for local dev setup
- [x] Update README with provisioning steps
- [x] Collect cookbooks for nginx, python, mysql, and other misc dependencies
- [ ] Create cookbook for the server itself to orchestrate our dependencies
- [ ] Figure out the best practice for deployment of a python app and connecting to nginx
- [x] Create encrypted data bag for mysql credentials
- [ ] Create encrypted data bags for twitter details
- [x] Add public keys for users that need access to the server itself (ask @livlab)

### CODE REVIEW

**Comment by tpitale** [comment]
@livlab What do you think about deploying with Heroku?

Benefits:
- Simple as can be
- Zero management/deployment on our part

Disadvantages:
- Cost (probably a bit more than DO)
- Database changes to postgresql from mysql

Feelings/Thoughts?

**Comment by tpitale** [comment]
So, I've gotten to a state where I'm working on the mysql setup and I've hit this: http://askubuntu.com/questions/457923/why-did-installation-of-mysql-5-6-on-ubuntu-14-04-fail #lolmysql

@livlab I can try to get the setup working on a bigger instance at digital ocean … but it'll be more expensive. Not sure what your plans are for running the site (beyond the week of IAS).

**Comment by tpitale** [comment]
The current branch runs on a 2GB VPS. That's $20 for one month.

**Comment by livlab** [comment]
Hey Tony, this is super awesome, thank you. I think this is a great plan (I don't have any particular opinion between postgresql over mysql). 

Didn't make a plan to run this beyond the summit (#19) so $20/month sounds great for now.  Let me know if there are any other steps I should take beyond merging your pull request.

**Comment by tpitale** [comment]
Oh no! I wasn't done with the full provisioning. Just the mysql bits. I'll open a new PR :smile:

**Comment by livlab** [comment]
LOL. I got SOOO excited.

**Comment by livlab** [comment]
Ok, this has been educational. Github makes the message very emphatic as in "Tony really wants you to merge this" rather than "hey this is in, make sure you check all the sub-tasks are done before you merge". Lesson learned!

**Comment by tpitale** [comment]
Yeah, I should have been more clear! I like to open PRs early to use them as a place for discussion as the "feature" evolves.

**Comment by livlab** [comment]
Makes sense to me. In that spirit, I will NOT touch this very inviting github message
image

**Pull request merged**
